api/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from api import views

router = DefaultRouter()
router.register(r'ies', views.IesViewSet)
router.register(r'campus', views.CampusViewSet)
router.register(r'cursos', views.CursoViewSet)
router.register(r'perfis', views.PerfilViewSet)

urlpatterns = [
    path('', include(router.urls)),
]

enem/urls.py
from django.urls import path
from enem import views

urlpatterns = [
    path('notas_prova/', views.NotasProvaView.as_view(), name='notas_prova'),
    path('notas_perfil/', views.NotasPerfilView.as_view(), name='notas_perfil'),
    path('comparar_perfis/', views.CompararPerfisView.as_view(), name='comparar_perfis'),
]

enem_sisu/urls.py
from django.contrib import admin
from django.contrib.auth.views import LogoutView
from django.urls import path, include
from sisu import views as core_views
from core.views import LoginView

urlpatterns = [
    path('api/', include('api.urls')),
    path('', include('administracao.urls')),
    path('', include('core.urls')),
    path('sisu/', include('sisu.urls')),
    path('enem/', include('enem.urls')),
    path('admin/', admin.site.urls),
    # path('select2/',  include('django_select2.urls')),

    # path('', core_views.index, name='index'),
    # path('cursos/', core_views.cursos, name='cursos'),
    # path('dados/', core_views.dados, name='dados'),
    # path('dados_tabelas/', core_views.dados_tabelas, name='dados_tabelas'),
    # path('dados_graficos/', core_views.dados_graficos, name='dados_graficos'),
    # path('registrar/', core_views.registrar, name='registrar'),
    # path('registrar-perfil/', core_views.registrar_perfil, name='registrar_perfil'),
    # path('consulta/', core_views.consulta, name='consulta')
]

enem/models.py
from django.db import models
from statistics import *

# Create your models here.

class TipoPerfil(models.Model):

    CHOICE_COR_RACA = (
        ('0', 'Não declarado',),
        ('1', 'Branca',),
        ('2', 'Preta',),
        ('3', 'Parda',),
        ('4', 'Amarela',),
        ('5', 'Indígena',),
    )

    CHOICE_ESCOLA = (
        ('1', 'Não informada',),
        ('2', 'Pública',),
        ('3', 'Privada',),
        ('4', 'Exterior',),
    )

    CHOICE_RENDA = (
        ('A', 'Nenhuma'),
        ('B', 'Até R$937,00'),
        ('C', 'de R$937,01 até R$1.405,50'),
        ('D', 'de R$1.405,51 até R$1.874,00'),
        ('E', 'de R$1.874,01 até R$2.342,50'),
        ('F', 'de R$2.342,51 até R$2.811,00'),
        ('G', 'de R$2.811,01 até R$3.748,00'),
        ('H', 'de R$3.748,01 até R$4.685,00'),
        ('I', 'de R$4.685,01 até R$5.622,00'),
        ('J', 'de R$5.622,01 até R$6.559,00'),
        ('K', 'de R$6.559,01 até R$7.496,00'),
        ('L', 'de R$7.496,01 até R$8.433,00'),
        ('M', 'de R$8.433,01 até R$9.370,00'),
        ('N', 'de R$9.370,01 até R$11.244,00'),
        ('O', 'de R$11.244,01 até R$14.055,00'),
        ('P', 'de R$14.055,01 até R$18.740,00'),
        ('Q', 'Acima de R$18.740,01'),
    )

    cor_raca = models.CharField(max_length=20, choices=CHOICE_COR_RACA, null=False)
    tipo_escola = models.CharField(max_length=50, choices=CHOICE_ESCOLA, null=False)
    renda_familiar = models.CharField(max_length=255, choices=CHOICE_RENDA, null=False)

    class Meta:
        verbose_name = "Tipo de Perfil"
        verbose_name_plural = "Tipos de Perfis"

    def media_perfil(self):
        notas = self.notas()
        media = median(notas)
        return media

    def notas(self):
        return [round(area.media, 2) for area in self.areas.all()]

    def __str__(self):
        return "%s%s%s" % (self.cor_raca, self.renda_familiar, self.tipo_escola)


class Area(models.Model):

    CHOICE_PROVAS = (
        ('LC', 'Linguagens e códigos'),
        ('MT', 'Matématica e suas Tecnologias'),
        ('CH', 'Ciências Humanas'),
        ('CN', 'Ciências da Natureza'),
        ('REDACAO', 'Redação')
    )

    prova = models.TextField(max_length=255, choices=CHOICE_PROVAS, null=False)
    frequencia = models.IntegerField()
    media = models.FloatField(default=0.00, null=False)
    variancia = models.FloatField(default=0.00, null=False)

    perfil = models.ForeignKey(TipoPerfil, on_delete=models.CASCADE, related_name='areas')

    def __str__(self):
        return "%.2f" % (self.media)


class Percentil(models.Model):

    valor = models.IntegerField(null=False)
    frequencia = models.IntegerField(null=False)
    media = models.FloatField(default=0.00, null=False)

    area = models.ForeignKey(Area, on_delete=models.CASCADE, related_name='percentis')

    class Meta:
        verbose_name_plural = "Percentis"

enem/views.py
from django.core.paginator import Paginator
from django.db.models import When, Case, Value, CharField, Sum
from django.shortcuts import render
from django.views import View

from enem.models import TipoPerfil, Percentil


class NotasPerfilView(View):
    context = {}
    context['titulo_pagina'] = "Notas médias por Perfil"

    def get(self, request):
        perfis_list = TipoPerfil.objects.all()
        self.context['perfis'] = perfis_list

        meu_perfil = TipoPerfil.objects.get(cor_raca=request.user.perfil.tipo_perfil.cor_raca,
                                            renda_familiar=request.user.perfil.tipo_perfil.renda_familiar,
                                            tipo_escola=request.user.perfil.tipo_perfil.tipo_escola)
        self.context['meu_perfil'] = meu_perfil

        return render(request, 'medias_perfis.html', self.context)


class NotasProvaView(View):
    context = {}
    context['titulo_pagina'] = "Notas por Prova"

    def get(self, request):
        percentis_total = {}
        for area in request.user.perfil.tipo_perfil.areas.all():
            percentis = self.calcula_percentis(area)
            frequencias = [percentil['frequencia__sum'] for percentil in percentis]
            total = sum(frequencias)
            frequencias = [round(item/total, 1)*100 for item in frequencias]
            percentis_total[area.prova.lower()] = frequencias

        self.context['percentis'] = percentis_total

        return render(request, 'notas_prova.html', self.context)

    def calcula_percentis(self, area):
        percentis = Percentil.objects.filter(area=area).annotate(faixa_tempo=Case(
            When(valor__in=range(1, 300), then=Value("ate 300")),
            When(valor__in=range(301, 400), then=Value('entre 201 e 400')),
            When(valor__in=range(401, 500), then=Value('entre 401 e 500')),
            When(valor__in=range(501, 600), then=Value('entre 501 e 600')),
            When(valor__in=range(601, 700), then=Value('entre 601 e 700')),
            When(valor__in=range(701, 800), then=Value('entre 701 e 800')),
            When(valor__in=range(801, 900), then=Value('entre 801 e 900')),
            default=Value('acima de 800'),
            output_field=CharField(), )
        )

        return percentis.values('faixa_tempo').annotate(Sum('frequencia')).order_by('faixa_tempo')

class CompararPerfisView(View):
    context = {}
    context['titulo_pagina'] = 'Comparar Perfis'

    def get(self, request):
        return render(request, 'comparar_perfis.html', self.context)

enem/templates/comparar_perfis.html
{% extends 'base.html' %}

{% block 'header_body' %}
    <ol class="breadcrumb bg-white">
        <li class="breadcrumb-item"><a href="#">ENEM</a></li>
        <li class="breadcrumb-item">{{ titulo_pagina }}</li>
    </ol>
{% endblock %}

{% block 'container_body' %}

{% endblock %}

enem/templates/medias_perfis.html
{% extends 'base.html' %}

{% block 'header_body' %}

    <ol class="breadcrumb bg-white">
        <li class="breadcrumb-item"><a href="#">ENEM</a></li>
        <li class="breadcrumb-item">{{ titulo_pagina }}</li>
    </ol>
{% endblock %}

{% block 'container_body' %}

    <div class="row mb-4">
        <div class="col-lg-6">
            <div class="card ">
                <div class="card-header">
                    <h5 class="card-title text-muted mb-0">SUAS NOTAS vs SEU PERFIL</h5>
                </div>
                <div class="card-body">
                    <canvas id="minhas-notas-radar" width="600" height="400"></canvas>
                </div>
            </div>
        </div>

        <div class="col-lg-6">
            <div class="card card-stats">
                <div class="card-header">
                    <h5 class="card-title text-uppercase text-muted mb-0">Notas meu perfil</h5>
                </div>
                <div class="card-body">
                    <canvas id="minhas-notas-bar" width="600" height="400"></canvas>
                </div>
            </div>
        </div>
    </div>

    <div class="card">
        <div class="card-body">
            <div class="table-responsive">
            <table class="table align-items-center" id="tabela-perfis">
                <thead class="thead-light">
                    <tr>
                        <th>Cor/Raça</th>
                        <th>Escola</th>
                        <th>Renda Familiar</th>
                        <th>Linguagens</th>
                        <th>Matemática</th>
                        <th>Redação</th>
                        <th>Ciências Humanas</th>
                        <th>Ciências da Natureza</th>
                    </tr>
                </thead>
                <tbody>
                    {% for perfil in perfis %}
                        <tr>
                            <td>{{ perfil.get_cor_raca_display }}</td>
                            <td>{{ perfil.get_tipo_escola_display }}</td>
                            <td>{{ perfil.get_renda_familiar_display }}</td>
                            <td>{{ perfil.areas.filter.1 }}</td>
                            <td>{{ perfil.areas.filter.2 }}</td>
                            <td>{{ perfil.areas.filter.0 }}</td>
                            <td>{{ perfil.areas.filter.4 }}</td>
                            <td>{{ perfil.areas.filter.3 }}</td>
                        </tr>
                    {% endfor%}
                </tbody>
            </table>
        </div>
        </div>
    </div>
{% endblock %}

{% block 'js_code' %}
    var ctxNotasRadar = document.getElementById('minhas-notas-radar');
    var ctxNotasBar = document.getElementById('minhas-notas-bar');

    options = {
        scale: {
            angleLines: {
                display: false
            },
            ticks: {
                suggestedMin: 0,
                suggestedMax: 1000
            }
        }
    };

    optionsBar = {
        "animation": animacao,
        scales: {
            yAxes: [{
                display: true,
                ticks: {
                    beginAtZero: true,
                    suggestedMax: 1000
                }
            }]
        }
    };

    data = {
        labels: ['Linguagens', 'Matemática', 'Redação', 'Humanas', 'Natureza'],
        datasets: [{
            data: {{ user.perfil.notas }},
            label: 'Minhas Notas',
            backgroundColor: 'rgba(55, 89, 252, 0.6)',
            borderColor: 'rgba(55, 89, 252, 0.8)',
        },{
            data: {{ meu_perfil.notas }},
            label: 'Meu Perfil',
            backgroundColor: 'rgba(255, 79, 82, 0.6 )',
            borderColor: 'rgba(255, 79, 82, 0.8)',
        }],
        borderWidth: 0.5
    };

    var myRadarChart = new Chart(ctxNotasRadar, {
        type: 'radar',
        data: data,
        options: options
    });

    var myBarChart = new Chart(ctxNotasBar, {
        type: 'bar',
        data: data,
        options: optionsBar,
    });

{% endblock %}

enem/templates/notas_prova.html
{% extends 'base.html' %}

{% block 'container_body' %}
    <div class="row mb-4">
        <div class="col-lg-4">
            <div class="card card-stats">
                <!-- Card body -->
                <div class="card-body"  style="min-height: 110px">
                    <div class="row">
                        <div class="col">
                            <h5 class="card-title text-uppercase text-muted mb-0">Tipo de Escola</h5> <br>
                            <span class="h3 font-weight-bold mb-0">{{ user.perfil.tipo_perfil.get_tipo_escola_display }}</span>
                        </div>

                        <div class="col-auto">
                            <div class="icon icon-shape bg-green text-white rounded-circle shadow">
                                <i class="ni ni-building"></i>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="col-lg-4">
            <div class="card card-stats">
                <!-- Card body -->
                <div class="card-body"  style="min-height: 110px">
                    <div class="row">
                        <div class="col">
                            <h5 class="card-title text-uppercase text-muted mb-0">Renda Familiar</h5>
                        </div>
                        <div class="col-auto">
                            <div class="icon icon-shape bg-blue text-white rounded-circle shadow">
                                <i class="ni ni-tag"></i>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col">
                            <span class="h3 font-weight-bold mb-0">{{ user.perfil.tipo_perfil.get_renda_familiar_display }}</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="col-lg-4">
            <div class="card card-stats">
                <!-- Card body -->
                <div class="card-body"  style="min-height: 110px">
                    <div class="row">
                        <div class="col">
                            <h5 class="card-title text-uppercase text-muted mb-0">Cor/Raça</h5>
                            <br>
                            <span class="h3 font-weight-bold mb-0">{{ user.perfil.tipo_perfil.get_cor_raca_display }}</span>
                        </div>

                        <div class="col-auto">
                            <div class="icon icon-shape bg-red text-white rounded-circle shadow">
                                <i class="ni ni-badge"></i>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="row mb-4">
        <div class="col-lg-12">
            <div class="card">
                <div class="card-header">
                    <h5 class="card-title text-muted mb-0">NOTAS - REDAÇÃO </h5>
                </div>
                <div class="card-body">
                    <canvas id="faixas-notas-redacao-bar" width="280" height="100"></canvas>
                </div>
            </div>
        </div>
    </div>

    <div class="row mb-4">
        <div class="col-lg-12">
            <div class="card">
                <div class="card-header">
                    <h5 class="card-title text-muted mb-0">NOTAS - LINGUAGENS </h5>
                </div>
                <div class="card-body">
                    <canvas id="faixas-notas-lc-bar" width="280" height="100"></canvas>
                </div>
            </div>
        </div>
    </div>

    <div class="row mb-4">
        <div class="col-lg-12">
            <div class="card">
                <div class="card-header">
                    <h5 class="card-title text-muted mb-0">NOTAS - MATEMÁTICA </h5>
                </div>
                <div class="card-body">
                    <canvas id="faixas-notas-mt-bar" width="280" height="100"></canvas>
                </div>
            </div>
        </div>

    </div>

    <div class="row mb-4">
        <div class="col-lg-12">
            <div class="card">
                <div class="card-header">
                    <h5 class="card-title text-muted mb-0">NOTAS - NATUREZA </h5>
                </div>
                <div class="card-body">
                    <canvas id="faixas-notas-cn-bar" width="280" height="100"></canvas>
                </div>
            </div>
        </div>
    </div>

    <div class="row mb-4">
        <div class="col-lg-12">
            <div class="card">
                <div class="card-header">
                    <h5 class="card-title text-muted mb-0">NOTAS - HUMANAS </h5>
                </div>
                <div class="card-body">
                    <canvas id="faixas-notas-ch-bar" width="280" height="100"></canvas>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block 'js_code' %}
    var ctxFaixasBarRedacao = document.getElementById('faixas-notas-redacao-bar');
    var ctxFaixasBarLC = document.getElementById('faixas-notas-lc-bar');
    var ctxFaixasBarMT = document.getElementById('faixas-notas-mt-bar');
    var ctxFaixasBarCN = document.getElementById('faixas-notas-cn-bar');
    var ctxFaixasBarCH = document.getElementById('faixas-notas-ch-bar');
    faixas = ['até 300', '301 a 400', '401 a 500', '501 a 600', '601 a 700', '701 a 800', '801 a 900', 'Acima de 900']

    data_rd = {
        labels: faixas,
        datasets: [{
            data: {{ percentis.redacao }},
            label: 'Perc. Alunos',
            backgroundColor: 'rgba(55, 89, 252, 0.6)',
            borderColor: 'rgba(55, 89, 252, 0.8)',
        }]
    };

    data_lc = {
        labels: faixas,
        datasets: [{
            data: {{ percentis.lc }},
            label: 'Perc. Alunos',
            backgroundColor: 'rgba(55, 89, 252, 0.6)',
            borderColor: 'rgba(55, 89, 252, 0.8)',
        }]
    };

    data_mt = {
        labels: faixas,
        datasets: [{
            data: {{ percentis.mt }},
            label: 'Perc. Alunos',
            backgroundColor: 'rgba(55, 89, 252, 0.6)',
            borderColor: 'rgba(55, 89, 252, 0.8)',
        }]
    };

    data_ch = {
        labels: faixas,
        datasets: [{
            data: {{ percentis.ch }},
            label: 'Perc. Alunos',
            backgroundColor: 'rgba(55, 89, 252, 0.6)',
            borderColor: 'rgba(55, 89, 252, 0.8)',
        }]
    };

    data_cn = {
        labels: faixas,
        datasets: [{
            data: {{ percentis.cn }},
            label: 'Perc. Alunos',
            backgroundColor: 'rgba(55, 89, 252, 0.6)',
            borderColor: 'rgba(55, 89, 252, 0.8)',
        }]
    };

    var myBarChart = new Chart(ctxFaixasBarRedacao, {
        type: 'bar',
        data: data_rd,
        options: {
            "animation": animacao_perc,
            legend: {
                display: true,
                position: 'bottom'
            },
            scales: {
                yAxes: [{
                    gridLines: {
                        display: true,
                        drawOnChartArea: false,
                    }
                }],
            }
        }
    });

    var myBarChart = new Chart(ctxFaixasBarLC, {
        type: 'bar',
        data: data_lc,
        options: {
            "animation": animacao_perc,
            legend: {
                display: true,
                position: 'bottom'
            },
            scales: {
                yAxes: [{
                    gridLines: {
                        display: true,
                        drawOnChartArea: false,
                    }
                }],
            }
        }
    });

    var myBarChart = new Chart(ctxFaixasBarMT, {
        type: 'bar',
        data: data_mt,
        options: {
            "animation": animacao_perc,
            legend: {
                display: true,
                position: 'bottom'
            },
            scales: {
                yAxes: [{
                    gridLines: {
                        display: true,
                        drawOnChartArea: false,
                    }
                }],
            }
        }
    });

    var myBarChart = new Chart(ctxFaixasBarCN, {
        type: 'bar',
        data: data_cn,
        options: {
            "animation": animacao_perc,
            legend: {
                display: true,
                position: 'bottom'
            },
            scales: {
                yAxes: [{
                    gridLines: {
                        display: true,
                        drawOnChartArea: false,
                    }
                }],
            }
        }
    });

    var myBarChart = new Chart(ctxFaixasBarCH, {
        type: 'bar',
        data: data_ch,
        options: {
            "animation": animacao_perc,
            legend: {
                display: true,
                position: 'bottom'
            },
            scales: {
                yAxes: [{
                    gridLines: {
                        display: true,
                        drawOnChartArea: false,
                    }
                }],
            }
        }
    });

{% endblock %}